"""empty message

Revision ID: 0a21bdadaa2a
Revises: None
Create Date: 2018-01-06 22:53:22.959165

"""

# revision identifiers, used by Alembic.
revision = '0a21bdadaa2a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_softwares')
    op.drop_table('users')
    op.drop_table('versiondb')
    op.add_column('spots', sa.Column('near_by_places', sa.String(), nullable=True))
    op.add_column('spots', sa.Column('similar_places', sa.String(), nullable=True))
    op.add_column('spots', sa.Column('special_attraction', sa.String(), nullable=True))
    op.add_column('spots', sa.Column('things_to_do', sa.String(), nullable=True))
    op.add_column('spots', sa.Column('time_to_visit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'time_to_visit')
    op.drop_column('spots', 'things_to_do')
    op.drop_column('spots', 'special_attraction')
    op.drop_column('spots', 'similar_places')
    op.drop_column('spots', 'near_by_places')
    op.create_table('versiondb',
    sa.Column('software_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('versions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num_of_ver', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('initial_release', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('software_id', name='versiondb_pkey')
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('similar_softwares',
    sa.Column('software_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alternatives', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('software_id', name='similar_softwares_pkey')
    )
    # ### end Alembic commands ###
