"""empty message

Revision ID: 3e954c27d89e
Revises: None
Create Date: 2018-01-06 16:22:41.501542

"""

# revision identifiers, used by Alembic.
revision = '3e954c27d89e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_softwares')
    op.drop_table('versiondb')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('versiondb',
    sa.Column('software_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('versions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num_of_ver', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('initial_release', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('software_id', name='versiondb_pkey')
    )
    op.create_table('similar_softwares',
    sa.Column('software_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alternatives', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('software_id', name='similar_softwares_pkey')
    )
    # ### end Alembic commands ###
