"""empty message

Revision ID: db921d5258fd
Revises: None
Create Date: 2018-01-07 00:48:18.934591

"""

# revision identifiers, used by Alembic.
revision = 'db921d5258fd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('how_to_reach', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'how_to_reach')
    # ### end Alembic commands ###
